require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels");
require('home.js');
require('product.js');
require('cooking.js');
require('flash.js');
require('cooking_category.js');
require("bootstrap/dist/js/bootstrap");
require("jquery");
